### PR TITLE
Update Games Readme 

### PR DESCRIPTION
**Pull request by Lea-S**
Updated Readme for Package usage

### CODE REVIEW

**Review by Fulachs — APPROVED** [review]
Great Work! 11/10 would review again.

**Review by NoWo2000 — APPROVED** [review]

**Comment by NoWo2000** [comment]
The most beautiful README I have ever seen.

**Review by NatiBckr — APPROVED** [review]

**Comment by Fulachs** [comment]
Nice! #69

**Comment by NoWo2000** [comment]
[Yes](https://sportkamasutra.com/)

**Pull request merged**
